BravissBlog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from blog.views import HomePageView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap
from django.views.generic.base import TemplateView

sitemaps = {
    'articles' : ArticleSitemap,
}

urlpatterns = [
    path("sitemap.xml",
         sitemap,
         {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt",
         TemplateView.as_view(template_name="robots.txt",
                              content_type="text/plain")
         ),
    path('admin/doc/',
         include('django.contrib.admindocs.urls')),
    path('admin/',
         admin.site.urls),
    path('tinymce/',
         include('tinymce.urls')),
]

urlpatterns += i18n_patterns(
    path('',
         HomePageView.as_view(), name='home'),
    path('accounts/',
         include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blog/',
         include(('blog.urls', 'blog'), namespace='blog')),
    path('i18n/',
         include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import (CustomLoginView,
                            PasswordResetView,
                            PasswordResetConfirmView,
                            PaymentPageView)
from accounts import views


urlpatterns = [
    path('login/',
         CustomLoginView.as_view(), name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<str:username>',
         views.UserProfileView.as_view(), name='user_profile'),
    path('register/',
         views.RegistrationView.as_view(), name='register'),
    path('password_reset/',
         PasswordResetView.as_view(),
         name='password_reset'),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('payment',
         PaymentPageView.as_view(), name='payment'),
    # path('edit/<str:username>',
    #      views.UserProfileView.as_view(), name='user_profile'),
]

blog/urls.py
from django.urls import path
from blog import views
from blog.views import update_publish_date

urlpatterns = [
    path('articles',
         views.ArticleListView.as_view(),
         name='article_list'),
    path('users/<str:username>/articles/',
         views.UserArticleListView.as_view(),
         name='user_articles'),
    path('articles/<slug:slug>',
         views.ArticleDetailView.as_view(),
         name='article_detail'),
    path('article/create',
         views.ArticleCreateView.as_view(),
         name='article_create'),
    path('article/update/<slug:slug>/',
         views.ArticleUpdateView.as_view(),
         name='article_update'),
    path('article/delete/<slug:slug>',
         views.ArticleDeleteView.as_view(),
         name='article_delete'),

    path('article/raise/<slug:slug>',
         views.ArticleRaiseView.as_view(),
         name='article_raise'),

    path('update_publish_date/<slug:slug>/',
         update_publish_date,
         name='update_publish_date'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
import uuid
from django.db import models

class EmployeeManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Employee(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = models.CharField(max_length=12, default='', blank=False, null=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='media/avatar')

    objects = EmployeeManager()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

accounts/forms.py
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth.forms import AuthenticationForm

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from accounts.models import Employee


class CustomLoginForm(AuthenticationForm):
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox,
    )


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox,
    )

    class Meta:
        model = Employee
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth.views import (LoginView,
                                       PasswordResetConfirmView as BasePasswordResetConfirmView,
                                       PasswordResetView as BasePasswordResetView)
from django.shortcuts import get_object_or_404
from accounts.forms import CustomLoginForm
from django.urls import reverse_lazy
from django.utils.http import url_has_allowed_host_and_scheme
from accounts.forms import RegistrationForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView, DetailView, TemplateView,
)

from accounts.models import Employee


class PaymentPageView(LoginRequiredMixin,
                      TemplateView):
    template_name = 'payment.html'


class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = CustomLoginForm

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url and url_has_allowed_host_and_scheme(
                url=next_url,
                allowed_hosts={self.request.get_host()},
                require_https=self.request.is_secure(),
        ):
            return next_url

        return reverse_lazy('home')


class UserProfileView(LoginRequiredMixin, DetailView):
    model = Employee
    template_name = 'user_profile.html'
    context_object_name = 'user_profile'

    def get_object(self, queryset=None):
        return get_object_or_404(Employee, username=self.kwargs['username'])


class RegistrationView(CreateView):
    model = Employee
    form_class = RegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Your account has been created')
        return response


class PasswordResetView(BasePasswordResetView):
    email_template_name = 'password_reset_email.txt'
    html_email_template_name = 'password_reset_email.html'
    template_name = 'password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetConfirmView(BasePasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'password_reset_confirm.html'

templates/article_detail.html
{% extends "base_2.html" %}
{% load social_share %}

{% block title %}{{ object.title }}{% endblock title %}

{% block og-title %}{{ article.title }}{% endblock %}
{% block og-description %}shered by {{ article.body }}{% endblock %}
{% block og-image %}http://{{ request.META.HTTP_HOST }}{{ article.image.url }}{% endblock %}

{% block page_title %}{{ object.title }}{% endblock %}

{% block content %}

    <ul class="nav mb-2">
        {% if request.user == article.author %}
            <li class="nav-item mr-2">
                <a href="{% url 'blog:article_update' article.slug %}" class="nav-link btn btn-primary">
                    <i class="bi bi-gear"></i>
                </a>
            </li>
            <li class="nav-item mr-2">
                <a href="{% url 'blog:article_raise' article.slug %}" class="nav-link btn btn-primary">
                    <i class="bi bi-badge-ad"></i>
                </a>
            </li>
            <li class="nav-item mr-2">
                <a href="{% url 'blog:article_delete' article.slug %}" class="nav-link btn btn-danger">
                    <i class="bi bi-trash"></i>
                </a>
            </li>
        {% endif %}
        <li class="nav-item mr-2">
            <button type="button" class="nav-link btn btn-primary" data-toggle="modal"
                    data-target="#exampleModalCenter">
                <i class="bi bi-share"></i>
            </button>
        </li>
    </ul>


    <div class="card mb-3">
        <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
        <div class="card-body mt-4">

            <p class="card-text">{{ object.body|safe }}</p>
            <p class="card-text"><small class="text-muted">{{ article.created_at|timesince }}</small></p>



            <span class="btn btn-primary">
                {{ object.author.username }}
            </span>
            <span class="btn btn-primary">
                <i class="bi bi-eye"></i>
                {{ object.views }}
            </span>
        </div>
    </div>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Share {{ object.title }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Share link</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               value="https://adearn{{ object.get_absolute_url }}">
                    </div>
                    {% post_to_telegram "{{object.title}}" object.get_absolute_url %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article_list.html
{% extends 'base_2.html' %}
{% load i18n %}


{% block title %}Article List{% endblock title %}

{% block page_title %}
    Articles
    <a href="{% url 'blog:article_create' %}"
       class="btn btn-primary float-right">{% trans 'Create' %}</a>
{% endblock %}

{% block content %}



    {# Article card #}
    <div class="row">
        {% for article in articles %}
            <div class="col-md-12">
                <div class="card mb-4 box-shadow">
                    <span class="position-absolute text-dark px-2 rounded bg-light"
                          style="top:10px;right:10px;">{{ article.created_at|date:"d.m.Y" }}</span>
                    <img class="card-img-top" src="{{ article.image.url }}" alt="{{ article.title }}">
                    <div class="card-body mt-2">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">{{ article.body|truncatewords:20|safe }}</p>
                        <p class="card-text"><small class="text-muted"><a
                                href="{% url 'blog:user_articles' article.author %}">{{ article.author.username }}</a> |
                            <i
                                    class="bi bi-eye"></i> {{ article.views }}</small></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if article.status == "pe" %}
                                    <span href="" class="btn btn-secondary mb-0 float-right">{% trans 'Pending' %} <i
                                            class="bi bi-stopwatch"></i></span>
                                {% else %}
                                    <a href="{% url 'blog:article_detail' article.slug %}"
                                       class="btn btn-primary float-right">{% trans 'View' %}</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {# Pagination navigation #}
    <nav aria-label="Page navigation example mx-auto">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page=1" class="page-link">&laquo; Перша</a></li>
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}"
                                         class="page-link">Попередня</a></li>
            {% endif %}
            <li class="page-item">
                <span class="page-link">
                    Сторінка {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                </span>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Наступна</a>
                </li>
                <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Остання
                    &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/base.html
{% load i18n %}
{% load static %}
{% load view_breadcrumbs %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Django blog platform">
    <meta name="keywords" content="Django, blog, meta">

    <meta property="og:type" content="website">
    <meta property="og:url" content="http://{{ request.META.HTTP_HOST }}{{ request.path }}">
    <meta property="og:title" content="{% block og-title %}{% endblock %}">
    <meta property="og:description" content="{% block og-description %}{% endblock %}">
    <meta property="og:image" content="{% block og-image %}{% endblock %}">

    <title>{% block title %}Django Hillel App{% endblock title %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.8.2/tinymce.min.js"
            integrity="sha512-6JR4bbn8rCKvrkdoTJd/VFyXAN4CE9XMtgykPWgKiHjou56YDJxWsi90hAeMTYxNwUnKSQu9JPc3SQUg+aGCHw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <style>
        .dropdown-toggle::after {
            display: none !important;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="{% url 'home' %}">ADEARN</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">{% trans 'Home' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:article_list' %}">{% trans 'Articles' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">{% trans 'Tasks' %}</a>
            </li>
        </ul>
        {% if user.is_authenticated %}

            {# Dropdown account link #}
            <ul class="navbar-nav">
                <li class="nav-item dropdown btn btn-primary dropdown-toggle mr-2">
                    <a class="nav-link dropdown-toggle p-0 text-white" href="/" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:user_profile' user.username %}">
                                {% trans 'Profile' %}
                                <i class="bi bi-person"></i>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:user_profile' user.username %}">
                                {% trans 'Balance' %}: {{ user.balance }}
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'blog:user_articles' user.username %}">
                                {% trans 'My article' %}
                                <i class="bi bi-folder"></i>
                            </a>
                        </li>

                        <li>
                            <a class="dropdown-item" href="/admin">
                                Admin panel
                            </a>
                        </li>

                        <li>
                            <div class="dropdown-divider"></div>
                            <form method="post" action="{% url 'accounts:logout' %}">
                                {% csrf_token %}
                                <input type="submit" value="{% trans 'Logout' %}" class="dropdown-item">
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
            {# Button login and register #}
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-primary mr-2">{% trans 'Login' %}</a>
            <a href="{% url 'accounts:register' %}" class="btn btn-primary mr-2">{% trans 'Register' %}</a>
        {% endif %}
        {# Dropdown languages #}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle p-0" style="height: 35px;" href="/" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {% if request.LANGUAGE_CODE == 'uk' %}
                        <img src="{% static 'icons/ua.svg' %}" alt="" style="height: 35px;">
                    {% else %}
                        <img src="{% static 'icons/um.svg' %}" alt="" style="height: 35px;">
                    {% endif %}
                </a>
                <form action="{% url 'set_language' %}" method="post" id="lang_form">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <li>
                                <button type="submit" name="language" value="{{ language.code }}"
                                        class="{% if language.code == LANGUAGE_CODE %}selected{% else %}demo-text-black{% endif %} dropdown-item">
                                    {{ language.name_local }}
                                </button>
                            </li>
                        {% endfor %}
                    </ul>
                </form>
                </a>
            </li>
        </ul>
    </div>
</nav>
<div class="container mt-3">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    {% block breadcrumbs %}
        {% render_breadcrumbs %}
    {% endblock %}
    {% block content %}
    {% endblock content %}

</div>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'link',
    });
</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/breadcrumbs.html
{#{% extends "base_2.html" %}#}
{##}
{#{% block body %}#}
{#    <ul>#}
{#    {% for pathname, path_url in view_paths %}#}
{#        <li>#}
{#            <a href="{{ path_url }}">{{ pathname }}</a>#}
{#        </li>#}
{#    {% endfor %}#}
{#    </ul>#}
{#{% endblock %}#}

templates/home.html
{% extends 'base_2.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome!</h1>
        <p class="lead">This is a simple home page for the ADearn application.</p>
        <hr class="my-4">
        <p class="lead">
            <a class="btn btn-dark" href="{% url 'blog:article_list' %}" role="button">Article List</a>
        </p>
    </div>
{% endblock content %}

templates/login.html
{% extends "base_2.html" %}

{% block title %}Login{% endblock title %}

{% block page_title %}
    Login
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h2 class="text-center mt-3">Ви вже авторизовані</h2>
    {% else %}
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <input type="text" name="username"
                               class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username">
                        {% for error in form.username.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <input type="password" name="password"
                               class="form-control {% if form.password.errors %}is-invalid{% endif %}" id="id_password">
                        {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.captcha }}
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                    <a href="{% url 'accounts:password_reset' %}">Reset password</a> /
                    <a href="{% url 'accounts:register' %}">Registration</a>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>{% trans "Password Reset Complete" %}</h2>
        <p>{% trans "Your password has been set. You may go ahead and log in now." %}</p>
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">{% trans "Log in" %}</a>
    </div>
</div>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>{% trans "Enter New Password" %}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.new_password1.errors }}
            {{ form.new_password1 }}
            {{ form.new_password2.errors }}
            {{ form.new_password2 }}
            <button type="submit" class="btn btn-primary">{% trans "Reset my password" %}</button>
        </form>
    </div>
</div>
{% endblock %}

templates/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>{% trans "Password Reset Sent" %}</h2>
        <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>
        <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
    </div>
</div>
{% endblock %}

templates/password_reset_email.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset</title>
</head>
<body>
    <p>Hello,</p>
    <p>You received this email because a request was made to reset the password for your account.</p>
    <p>If you did not request this, please ignore this email.</p>
    <p>To reset your password, click the link below:</p>
    <p><a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Reset your password</a></p>
    <p>This link is valid for 48 hours.</p>
    <p>Thank you.</p>
</body>
</html>

templates/payment.html
{% extends 'base_2.html' %}

{% block title %}Payment{% endblock title %}

{% block page_title %}
    Payment
{% endblock %}

{% block content %}

{% endblock content %}

templates/post_to_telegram.html
 <a href="{{ telegram_url }}" class="btn btn-primary text-white" target="_blank"><i class="bi bi-telegram"></i></a>

templates/user_profile.html
{% extends "base_2.html" %}

{% block title %}{{ object.username }}{% endblock title %}

{% block page_title %}
    Profile
{% endblock %}

{% block content %}
    <div class="card p-3 py-4 mt-4">
        <div class="text-center">
            <img src="{{ object.avatar.url }}" width="100" height="100" class="rounded-circle">
        </div>
        <div class="text-center mt-3">
            <span class="bg-secondary p-1 px-4 rounded text-white">Status [soon]</span>
            <h5 class="mt-2 mb-0">{{ object.username }}</h5>

            <div class="buttons mt-4">
                <button class="btn btn-primary px-4 ms-3">Edit accounts</button>
            </div>

        </div>
    </div>

    <script>
        var username = "{{ user.username }}";
        var hasAvatar = "{{ user.has_avatar }}";

        function getRandomColor() {
            var letters = '0123456789ABCDEF';
            var color = '#';
            for (var i = 0; i < 6; i++) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
        }

        function createAvatar(username) {
            var firstLetter = username.charAt(0).toUpperCase();
            var color = getRandomColor();
            var avatarHTML = '<div class="avatar" style="background-color: ' + color + ';">' + firstLetter + '</div>';
            return avatarHTML;
        }

        if (!hasAvatar) {
            var avatarContainer = document.querySelector('.user-avatar');
            avatarContainer.innerHTML = createAvatar(username);
        }
    </script>
{% endblock %}